FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel

SHELL ["/bin/bash", "-c"]

# Deal with nvidia GPG key issues
# https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
ARG DISTRO=ubuntu1804
ARG ARCH=x86_64
RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-get update && apt-get install -y wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/$DISTRO/$ARCH/cuda-keyring_1.0-1_all.deb \
    && dpkg -i cuda-keyring_1.0-1_all.deb

# Install git/ssh/tmux
RUN apt-get update \
    && apt-get install -y git ssh tmux vim curl htop

# Use a non-root user
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN mkdir /home/condensed-sparsity/ && \
    chown -R $USER_GID:$USER_UID /home/condensed-sparsity/

ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

# Init conda
USER $USERNAME
RUN conda init bash \
    && sudo chmod -R +777 /opt/conda/ \
    && exec bash \ 
    && conda activate base

# Install poetry
# https://python-poetry.org/docs/configuration/#using-environment-variables
ENV POETRY_VERSION="1.2.0" \
    POETRY_HOME="/home/${USERNAME}/poetry" \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    BUILD_PATH="/home/${USERNAME}/build" \
    VENV_PATH="/home/${USERNAME}/build/.venv"

ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

RUN curl -sSL https://install.python-poetry.org | python3 -

# Install project requirements 
RUN mkdir ${BUILD_PATH}
WORKDIR ${BUILD_PATH}
COPY ./pyproject.toml ./poetry.lock ./
RUN exec bash
RUN python -m venv .venv && source .venv/bin/activate
RUN poetry install -vvv --no-root

WORKDIR /home/condensed-sparsity/
