FROM pytorch/pytorch:latest

# Install git/ssh
RUN apt-get update \
    && apt-get install -y git ssh

# Install project requirements
COPY requirements.txt /tmp/pip-tmp/
RUN conda init bash
RUN exec bash \
    && conda activate base \
    && conda install -c defaults -c conda-forge --file /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp

# Install dev requirements
COPY requirements-dev.txt /tmp/pip-tmp/
RUN conda install -c defaults -c conda-forge --file /tmp/pip-tmp/requirements-dev.txt \
    && rm -rf /tmp/pip-tmp

WORKDIR /home/condensed-sparsity/
