program: train_rigl.py
method: grid
entity: condensed-sparsity
project: condensed-rigl
name: vit_min_sal_sparse_mha
metric:
  goal: maximize
  name: accuracy
parameters:
  rigl.ignore_mha_layers:
    values: [True, False]
  rigl.dense_allocation:
    values:
      [0.5, 0.3, 0.25]
      # percentage of dense parameters allowed. if None, pruning will not
      # be used. must be on the interval (0, 1]
  rigl.min_salient_weights_per_neuron:
    values: [0.1, 0.3, 0.5, 0.7, 0.9, 0.95]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
