program: train_rigl.py
method: grid
entity: condensed-sparsity
project: condensed-rigl
name: vit_in_proj
metric:
  goal: maximize
  name: accuracy
parameters:
  rigl.dense_allocation: 
    values: [0.3]
      # percentage of dense parameters allowed. if None, pruning will not 
      # be used. must be on the interval (0, 1]
  rigl.keep_first_layer_dense:
    values: [True, False]
  rigl.ignore_mha_layers:
    values: [True, False]
  # rigl.min_salient_weights_per_neuron:
  #   values: [0.3, 0.5, 0.75, 0.9, 0.95, 0.99]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
